services:
  mydb:
    image: mongo:latest
    container_name: mydb
    ports:
      - "27017:27017"
    command: ["--bind_ip_all"]  # Permite conexões de fora do container sem autenticação
    # Não definimos MONGO_INITDB_ROOT_USERNAME nem PASSWORD

  mymongo-express:
    image: mongo-express:latest
    container_name: mymongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"  # Não requer usuário/admin
      ME_CONFIG_MONGODB_SERVER: mydb
    depends_on:
      - mydb

