name: build java

on:
  workflow_call:

jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'amzn'
    - name: "build java 25"
      run: mvn package
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
